In [ ]:
#pip install pandas

Requirement already satisfied: pandas in d:\depi\task\depi-bns5_ais2_s1\.venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in d:\depi\task\depi-bns5_ais2_s1\.venv\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\depi\task\depi-bns5_ais2_s1\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\depi\task\depi-bns5_ais2_s1\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in d:\depi\task\depi-bns5_ais2_s1\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
data = [[1,444,"abc"],
        [2,555,"def"],
        [3,666,"ghi"],
        [4,777,"jkl"]]
df = pd.DataFrame(data, columns=["Idx", "std_id", "Dept"])

In [4]:
df

   Idx  std_id Dept
0    1     444  abc
1    2     555  def
2    3     666  ghi
3    4     777  jkl

In [8]:
data2 = {'Idx': [1, 2, 3, 4],
      'std_id': [444, 555, 666, 777],
      'Dept': ['abc', 'def', 'ghi', 'jkl']}
df2 = pd.DataFrame(data2)
df2

   Idx  std_id Dept
0    1     444  abc
1    2     555  def
2    3     666  ghi
3    4     777  jkl

In [9]:
display(df2)
columns = ['Idx-1', 'std_id1', 'Depart']
df2.columns = columns
display(df2)

   Idx  std_id Dept
0    1     444  abc
1    2     555  def
2    3     666  ghi
3    4     777  jkl

   Idx-1  std_id1 Depart
0      1      444    abc
1      2      555    def
2      3      666    ghi
3      4      777    jkl

In [10]:
display(df2)
index = ['a', 'b', 'c', 'd']
df2.index = index
display(df2)

   Idx-1  std_id1 Depart
0      1      444    abc
1      2      555    def
2      3      666    ghi
3      4      777    jkl

   Idx-1  std_id1 Depart
a      1      444    abc
b      2      555    def
c      3      666    ghi
d      4      777    jkl

In [11]:
df.dtypes

Idx       int64
std_id    int64
Dept        str
dtype: object

In [12]:
df['std_id'] = df['std_id'].astype('category')

In [13]:
df.dtypes

Idx          int64
std_id    category
Dept           str
dtype: object

In [14]:
cols = ['Idx', 'Dept']
df[cols] = df[cols].astype('category')

In [15]:
df.dtypes

Idx       category
std_id    category
Dept      category
dtype: object

In [24]:
data2 = {'Idx': [1, 2, 3, 4],
      'std_id': [444, 555, 666, 777],
      'Dept': ['abc', 'def', 'ghi', 'jkl']}
df2 = pd.DataFrame(data2)
display(df2)
df2['Dept'] = df2['Dept'].astype('category')
df2.dtypes

   Idx  std_id Dept
0    1     444  abc
1    2     555  def
2    3     666  ghi
3    4     777  jkl

Idx          int64
std_id       int64
Dept      category
dtype: object

In [25]:
df2.head(2)

   Idx  std_id Dept
0    1     444  abc
1    2     555  def

In [26]:
df2.tail(2)

   Idx  std_id Dept
2    3     666  ghi
3    4     777  jkl

In [27]:
df2.describe()

            Idx      std_id
count  4.000000    4.000000
mean   2.500000  610.500000
std    1.290994  143.300384
min    1.000000  444.000000
25%    1.750000  527.250000
50%    2.500000  610.500000
75%    3.250000  693.750000
max    4.000000  777.000000

In [28]:
df2.describe(include = 'category')

       Dept
count     4
unique    4
top     abc
freq      1

In [30]:
df2.index
df2.columns

Index(['Idx', 'std_id', 'Dept'], dtype='str')

In [31]:
df2['std_id'].unique()

array([444, 555, 666, 777])

In [32]:
df2['std_id'].nunique()

4

In [35]:
df2['std_id'].idxmax()

3

In [36]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Idx     4 non-null      int64
 1   std_id  4 non-null      int64
 2   Dept    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 404.0 bytes

In [43]:
d = df2['Dept'].value_counts()
d

Dept
abc    1
def    1
ghi    1
jkl    1
Name: count, dtype: int64

In [44]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 777, 'jkl']], dtype=object)

In [46]:
df2.replace(444, 'faris', inplace=True)
df2

   Idx std_id Dept
0    1  faris  abc
1    2    555  def
2    3    666  ghi
3    4    777  jkl

In [47]:
df.std_id = df.std_id.map({444:"jdk", 555:"ksdjk"})

In [48]:
df

  Idx std_id Dept
0   1    jdk  abc
1   2  ksdjk  def
2   3    NaN  ghi
3   4    NaN  jkl

In [50]:
data2 = {'Idx': [1, 2, 3, 4],
      'std_id': [444, 555, 666, 777],
      'Dept': ['abc', 'def', 'ghi', 'jkl']}
df = pd.DataFrame(data2)
df

   Idx  std_id Dept
0    1     444  abc
1    2     555  def
2    3     666  ghi
3    4     777  jkl

In [ ]:
x = df.iloc[0:2, 0:2]

   Idx  std_id
0    1     444
1    2     555