In [1]:
import pandas as pd

In [3]:
data = pd.read_table('http://bit.ly/movieusers')
data.head()

   1|24|M|technician|85711
0       2|53|F|other|94043
1      3|23|M|writer|32067
2  4|24|M|technician|43537
3       5|33|F|other|15213
4   6|42|M|executive|98101

In [4]:
data.tail()

          1|24|M|technician|85711
937        939|26|F|student|33319
938  940|32|M|administrator|02215
939        941|20|M|student|97229
940      942|48|F|librarian|78209
941        943|22|M|student|77841

In [5]:
data = pd.read_table('http://bit.ly/movieusers', sep='|')
data.head()

   1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

In [6]:
data = pd.read_table('http://bit.ly/movieusers', sep='|', header=None)
data.head()

   0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [8]:
Header_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
data = pd.read_table('http://bit.ly/movieusers', sep='|', header=None, names=Header_cols)
data.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [9]:
user_info = pd.read_csv('http://bit.ly/uforeports')

In [10]:
type(user_info)

pandas.DataFrame

In [11]:
user_info.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [15]:
user_info['City'].head()

0                  Ithaca
1             Willingboro
2                 Holyoke
3                 Abilene
4    New York Worlds Fair
Name: City, dtype: str

In [16]:
user_info.City.tail()

18236     Grant Park
18237    Spirit Lake
18238    Eagle River
18239    Eagle River
18240           Ybor
Name: City, dtype: str

In [17]:
user_info['Colors Reported'].head()

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Colors Reported, dtype: str

In [18]:
user_info.shape

(18241, 5)

In [19]:
user_info.City + user_info.State

0                      IthacaNY
1                 WillingboroNJ
2                     HolyokeCO
3                     AbileneKS
4        New York Worlds FairNY
                  ...
18236              Grant ParkIL
18237             Spirit LakeIA
18238             Eagle RiverWI
18239             Eagle RiverWI
18240                    YborFL
Length: 18241, dtype: str

In [20]:
user_info.City + ', ' + user_info.State

0                      Ithaca, NY
1                 Willingboro, NJ
2                     Holyoke, CO
3                     Abilene, KS
4        New York Worlds Fair, NY
                   ...
18236              Grant Park, IL
18237             Spirit Lake, IA
18238             Eagle River, WI
18239             Eagle River, WI
18240                    Ybor, FL
Length: 18241, dtype: str

In [21]:
user_info['Location'] = user_info.City + ', ' + user_info.State
user_info.head()

,City,Colors Reported,Shape Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [22]:
user_info.to_csv('new_file.csv')

In [23]:
new_file = pd.read_csv('new_file.csv')
new_file.head()

,Unnamed: 0,City,Colors Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [24]:
new_file.describe()

         Unnamed: 0
count  18241.000000
mean    9120.000000
std     5265.867466
min        0.000000
25%     4560.000000
50%     9120.000000
75%    13680.000000
max    18240.000000

In [25]:
new_file.dtypes

Unnamed: 0         int64
City                 str
Colors Reported      str
Shape Reported       str
State                str
Time                 str
Location             str
dtype: object

In [27]:
new_file.describe(include= 'object')

C:\Users\Fahd\AppData\Local\Temp\ipykernel_29652\2783295091.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  new_file.describe(include= 'object')

,City,Colors Reported,Shape Reported,State,Time,Location
count,18215,2882,15597,18241,18241,18215
unique,6475,27,27,52,16145,8028
top,Seattle,RED,LIGHT,CA,11/16/1999 19:00,"Seattle, WA"
freq,187,780,2803,2529,27,187

In [28]:
new_file[1:5]

,Unnamed: 0,City,Colors Reported,Shape Reported,State,Time,Location
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [29]:
new_file.columns

Index(['Unnamed: 0', 'City', 'Colors Reported', 'Shape Reported', 'State',
       'Time', 'Location'],
      dtype='str')

In [30]:
new_file.info()

<class 'pandas.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       18241 non-null  int64
 1   City             18215 non-null  str
 2   Colors Reported  2882 non-null   str
 3   Shape Reported   15597 non-null  str
 4   State            18241 non-null  str
 5   Time             18241 non-null  str
 6   Location         18215 non-null  str
dtypes: int64(1), str(6)
memory usage: 997.7 KB

In [31]:
new_file.rename(columns={'Colors Reported': 'Colors_Reported'})

,Unnamed: 0,City,Colors_Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"
...,...,...,...,...,...,...,...
18236,18236,Grant Park,NaN,TRIANGLE,IL,12/31/2000 23:00,"Grant Park, IL"
18237,18237,Spirit Lake,NaN,DISK,IA,12/31/2000 23:00,"Spirit Lake, IA"
18238,18238,Eagle River,NaN,NaN,WI,12/31/2000 23:45,"Eagle River, WI"
18239,18239,Eagle River,RED,LIGHT,WI,12/31/2000 23:45,"Eagle River, WI"
18240,18240,Ybor,NaN,OVAL,FL,12/31/2000 23:59,"Ybor, FL"

In [32]:
new_file.columns

Index(['Unnamed: 0', 'City', 'Colors Reported', 'Shape Reported', 'State',
       'Time', 'Location'],
      dtype='str')

In [34]:
new_file.rename(columns={'Colors Reported': 'Colors_Reported'}, inplace=True)

In [35]:
new_file.columns

Index(['Unnamed: 0', 'City', 'Colors_Reported', 'Shape Reported', 'State',
       'Time', 'Location'],
      dtype='str')

In [36]:
new_file_columns = ['Index', 'City', 'Colors Reported', 'Shape Reported', 'State', 'Time', 'Location']

In [37]:
new_file.columns = new_file_columns

In [38]:
new_file.head()

,Index,City,Colors Reported,Shape Reported,State,Time,Location
0,0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca, NY"
1,1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro, NJ"
2,2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke, CO"
3,3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene, KS"
4,4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair, NY"

In [42]:
new_columns = ['City', 'Colors Reported', 'Shape Reported', 'State', 'Time']

In [43]:
ufo = pd.read_csv('http://bit.ly/uforeports', names= new_columns, header= 0)

In [45]:
ufo[:1]

     City Colors Reported Shape Reported State            Time
0  Ithaca             NaN       TRIANGLE    NY  6/1/1930 22:00

In [46]:
ufo.columns

Index(['City', 'Colors Reported', 'Shape Reported', 'State', 'Time'], dtype='str')

In [48]:
ufo.columns = ufo.columns.str.replace(' ', '_')

In [51]:
ufo.columns

Index(['City', 'Colors_Reported', 'Shape_Reported', 'State', 'Time'], dtype='str')

In [53]:
ufo.drop(['Colors_Reported', 'City'], axis=1, inplace=True)

In [54]:
ufo.head()

  Shape_Reported State             Time
0       TRIANGLE    NY   6/1/1930 22:00
1          OTHER    NJ  6/30/1930 20:00
2           OVAL    CO  2/15/1931 14:00
3           DISK    KS   6/1/1931 13:00
4          LIGHT    NY  4/18/1933 19:00

In [55]:
ufo.drop([0, 1, 2], axis=0, inplace=True)

In [56]:
ufo.head()

  Shape_Reported State             Time
3           DISK    KS   6/1/1931 13:00
4          LIGHT    NY  4/18/1933 19:00
5           DISK    ND  9/15/1934 15:30
6         CIRCLE    CA   6/15/1935 0:00
7           DISK    MI   7/15/1936 0:00

In [57]:
movies = pd.read_csv('http://bit.ly/imdbratings')

In [58]:
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [59]:
movies.title.sort_values()

542     (500) Days of Summer
5               12 Angry Men
201         12 Years a Slave
698                127 Hours
110    2001: A Space Odyssey
               ...
955         Zero Dark Thirty
677                   Zodiac
615               Zombieland
526                     Zulu
864                    [Rec]
Name: title, Length: 979, dtype: str

In [60]:
movies.title.sort_values(ascending=False)

864                    [Rec]
526                     Zulu
615               Zombieland
677                   Zodiac
955         Zero Dark Thirty
               ...
110    2001: A Space Odyssey
698                127 Hours
201         12 Years a Slave
5               12 Angry Men
542     (500) Days of Summer
Name: title, Length: 979, dtype: str

In [61]:
movies.sort_values('title')

,star_rating,title,content_rating,genre,duration,actors_list
542,7.8,(500) Days of Summer,PG-13,Comedy,95,"[u'Zooey Deschanel', u'Joseph Gordon-Levitt', ..."
5,8.9,12 Angry Men,NOT RATED,Drama,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
201,8.1,12 Years a Slave,R,Biography,134,"[u'Chiwetel Ejiofor', u'Michael Kenneth Willia..."
698,7.6,127 Hours,R,Adventure,94,"[u'James Franco', u'Amber Tamblyn', u'Kate Mara']"
110,8.3,2001: A Space Odyssey,G,Mystery,160,"[u'Keir Dullea', u'Gary Lockwood', u'William S..."
...,...,...,...,...,...,...
955,7.4,Zero Dark Thirty,R,Drama,157,"[u'Jessica Chastain', u'Joel Edgerton', u'Chri..."
677,7.7,Zodiac,R,Crime,157,"[u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M..."
615,7.7,Zombieland,R,Comedy,88,"[u'Jesse Eisenberg', u'Emma Stone', u'Woody Ha..."
526,7.8,Zulu,UNRATED,Drama,138,"[u'Stanley Baker', u'Jack Hawkins', u'Ulla Jac..."
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."

In [62]:
movies.sort_values(['content_rating', 'duration'])

,star_rating,title,content_rating,genre,duration,actors_list
713,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P..."
513,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80,"[u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga..."
272,8.1,The Killing,APPROVED,Crime,85,"[u'Sterling Hayden', u'Coleen Gray', u'Vince E..."
703,7.6,Dracula,APPROVED,Horror,85,"[u'Bela Lugosi', u'Helen Chandler', u'David Ma..."
612,7.7,A Hard Day's Night,APPROVED,Comedy,87,"[u'John Lennon', u'Paul McCartney', u'George H..."
...,...,...,...,...,...,...
387,8.0,Midnight Cowboy,X,Drama,113,"[u'Dustin Hoffman', u'Jon Voight', u'Sylvia Mi..."
86,8.4,A Clockwork Orange,X,Crime,136,"[u'Malcolm McDowell', u'Patrick Magee', u'Mich..."
187,8.2,Butch Cassidy and the Sundance Kid,NaN,Biography,110,"[u'Paul Newman', u'Robert Redford', u'Katharin..."
936,7.4,True Grit,NaN,Adventure,128,"[u'John Wayne', u'Kim Darby', u'Glen Campbell']"
649,7.7,Where Eagles Dare,NaN,Action,158,"[u'Richard Burton', u'Clint Eastwood', u'Mary ..."

In [63]:
booleans = []
for length in movies.duration:
    if length >= 200:
        booleans.append(True)
    else:
        booleans.append(False)

In [64]:
booleans[0:3]

[False, False, True]

In [65]:
len(booleans)

979

In [66]:
is_long = pd.Series(booleans)
is_long.head()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [68]:
is_long = movies.duration >=200
is_long.head()

0    False
1    False
2     True
3    False
4    False
Name: duration, dtype: bool

In [70]:
movies[is_long]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."

In [71]:
movies.loc[movies.duration >= 200, 'genre']

2          Crime
7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: str

In [72]:
movies[(movies.duration >= 200) & (movies.genre == 'Drama')]

,star_rating,title,content_rating,genre,duration,actors_list
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."